### ISSUE TITLE
Implementar Padrão de Projeto: Proxy

### ISSUE THREAD

**Issue by HugoOkumura** [HugoOkumura/padroes-de-projeto--BCC3004.ICE_CM#1]
Implemente um exemplo, em python, do Padrão de Projeto, Proxy. Demonstre um problema comum que possa utilizar o Proxy - ex: um código comentado no arquivo da implementação - e demonstre o código da solução utilizando o padrão.

**Comment by mattokgit44** [comment]
Comentário referente à solicitação do assigned
