### ISSUE TITLE
 Implementar Padrão de Projeto: Template Method

### ISSUE THREAD

**Issue by PedroHOCostaa** [HugoOkumura/padroes-de-projeto--BCC3004.ICE_CM#2]
Nesta issue deve ser abordado o Padrão de Projeto Template Method. nestá issue é necessario que seja apresentado os seguintes itens sobre o padrão de projeto:

- [ ] O conceito do padrão.
- [ ] Problema que ele resolve.
- [ ] Quando usar o padrão.
- [ ] Um diagrama UML que represente o conceito do padrão.
- [ ] Um exemplo de código-fonte com comentários explicativos.
- [ ] Vantagens e desvantagens.

**Comment by HugoOkumura** [comment]
Comentário pedindo para atribuição da issue
