### ISSUE TITLE
Implementar Padrão de Projeto: Adapter

### ISSUE THREAD

**Issue by DimitriGaraluz** [HugoOkumura/padroes-de-projeto--BCC3004.ICE_CM#5]
Nesta issue, deve ser abordado o Padrão de Projeto Adapter.
Os seguintes critérios devem ser apresentados sobre o padrão:

1. O conceito do padrão;
2. Problema que ele resolve;
3. Quando usar o padrão;
4. Um diagrama UML que represente o conceito do padrão;
5. Um exemplo de código-fonte com comentários explicativos;
6. Vantagens e desvantagens.

**Comment by PedroHOCostaa** [comment]
Solicito ser o assignee desta Issue.
